name=str(input("Enter the name of the student:"))
clas=int(input("Enter the clas of the student:"))
age=int(input("Enter the age of the student:"))
print(name,clas,age)
print("\r")
print("\r")
print(name)
print(clas)
print(age)